# Describes the format for available Husqvarna Automower services

blabla:
  description: Send a custom command to the mower (optional with duration).
  target:
    entity:
      integration: "husqvarna_automower"
  fields:
    command:
      # Field name as shown in UI
      name: Command
      # Description of the field
      description: Custom command
      # Whether or not field is required
      required: true
      # Example value that can be passed for this field
      example: "Start"
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control the input UI for this field
      selector:
        select:
          options:
            - "Start"
            - "ResumeSchedule"
            - "Pause"
            - "Park"
            - "ParkUntilNextSchedule"
            - "ParkUntilFurtherNotice"
    duration:
      # Field name as shown in UI
      name: Duration for the command
      # Description of the field
      description: Duration of the command (only for 'Start' and 'Park')
      # Whether or not field is required
      required: false
      # Example value that can be passed for this field
      example: "60"
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control the input UI for this field
      selector:
        number:
          min: 0
          unit_of_measurement: "min"
